### ISSUE TITLE
Add "Copy Text" buttons to SQL/CSV view

### ISSUE THREAD

**Issue by jrparish** [themmer/text-scripts#16]
When working with a lot of records it would be handy to have a button that would copy the text within the containers to the clipboard for easy copy/pasting.

**Comment by themmer** [comment]
I tried some things on this and could not get it working with the available javascript solutions out there. If you set focus on the textarea you can do the keyboard shortcuts of copy and paste pretty quick... the next best thing I could get you.

**Comment by jrparish** [comment]
Cool, that works for me :+1:
