### ISSUE TITLE
Add optional starting id for the SQL script

### ISSUE THREAD

**Issue by jrparish** [themmer/text-scripts#19]
Sometimes I need to add additional fields after the fact. For the SQL script it would be nice to be able to enter the starting id, so I can resume from the previous id where I left off. Then I could just append it to my existing script.

**Comment by themmer** [comment]
We could have a field that defaults to zero and passes that down the payload and the sql increments start from there. Not a big change

**Comment by themmer** [comment]
@jrparish This feature has been added
