### ISSUE TITLE
Use bank_structure instead of source_company_id

### ISSUE THREAD

**Issue by jaylarson99** [themmer/text-scripts#38]
First....Great tool!!!!

I got the following PR feedback on the sql generated: 
WHERE source_company_id = 'ROOT' 
should be
WHERE bank_structure = 'ROOT'

INSERT INTO company_attribute (created_ts,deleted,modified_by,modified_by_type,updated_ts,version,id,value_string,company_id,definition)
  VALUES (CURRENT_TIMESTAMP,0,'TCF-778','D3SCRIPT',CURRENT_TIMESTAMP,0,(SELECT id FROM id_seq WHERE tbl='company_attribute'),'4',(SELECT id FROM company WHERE source_company_id = 'ROOT'),'settings.profile.address.lines.allowed');
should be 
INSERT INTO company_attribute (created_ts,deleted,modified_by,modified_by_type,updated_ts,version,id,value_string,company_id,definition)
  VALUES (CURRENT_TIMESTAMP,0,'TCF-778','D3SCRIPT',CURRENT_TIMESTAMP,0,(SELECT id FROM id_seq WHERE tbl='company_attribute'),'4',(SELECT id FROM company WHERE bank_structure = 'ROOT'),'settings.profile.address.lines.allowed');

**Comment by themmer** [comment]
@jaylarson99  

l10n is using the proper one, but company attribute needs to be updated as you said. Thanks!

**Comment by themmer** [comment]
@jaylarson99  This fix is deployed
https://murmuring-wildwood-83806.herokuapp.com/companyAttribute
